units: map(include("unit"), key=str())
---
unit:
  remote_base_path: str()
  local_path: str()
  snapshot:
    type: enum("btrfs")
    path: str()
    name_template: str(required=False)
  backup: list(str())