name: Package deploy

on:
  push:
    tags:
      - "?[0-9]+."
      - "?[0-9]+.[0-9]+"
      - "?[0-9]+.[0-9]+.[0-9]+"
      - "?[0-9]+.[0-9]+.[0-9]+.[0-9]+"

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get version
        run: |
          VERSION="${GITHUB_REF/refs\/tags\//}"
          VERSION="${VERSION/v/}"
          echo ${VERSION} > ./VERSION
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Set the version
        run: |
          echo "__version__ = '$(cat VERSION)'" > ./yabu/version.py
      - name: Build
        run: |
          python setup.py sdist bdist_wheel
      - name: Calculate hash of the package
        run: |
          echo $(shasum -a 256 "dist/yabu-$(cat VERSION).tar.gz" | head -c 64) > ./SHA256
      - name: Deploy
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload dist/*
      - uses: actions/upload-artifact@v2
        with:
          name: metadata
          path: |
            VERSION
            SHA256

  aur:
    needs: pypi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: metadata
      - name: Prepare PKGBUILD
        run: |
          sed -i -E "s;pkgver=([\"\']?)[[:alnum:]\.\-]*\1;pkgver=\"$(cat VERSION)\";"  ./PKGBUILD
          sed -i -E "s;sha256sums=\([^\)]*\);sha256sums=(\"$(cat SHA256)\");" ./PKGBUILD
      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.3
        with:
          pkgname: python-yabu
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
